"""Builds poolean-external-data.js from the real Poolean site's own data export (an .xlsx someone
downloads from the site's export feature). Two things this app doesn't otherwise have:
  POOLEAN_RANKINGS  every party night's power-ranking result (rank/percentile per player), not
                     just the handful of nights that also have logged game film
  POOLEAN_RECORD     each player's real overall win-loss record across every game the site has
                      ever recorded, not just the subset re-logged shot-by-shot in this app
Awards are NOT in this file on purpose -- the export's own README says per-voter ballots are
deleted when a party closes, and a season still being voted on has no results yet at all. Copy
AWARD_RESULTS's existing entries in app.js by hand from the site once a season's voting closes,
the same way it's always been done.
Usage: python build_poolean_data.py PATH_TO_EXPORT.xlsx
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

import openpyxl

MONTHS = {"Jan": "01", "Feb": "02", "Mar": "03", "Apr": "04", "May": "05", "Jun": "06",
          "Jul": "07", "Aug": "08", "Sep": "09", "Oct": "10", "Nov": "11", "Dec": "12"}


def party_date_to_iso(label, year=2026):
    # "Sun Jun 7" -> "2026-06-07". The export has no year (README: single season, no year in it).
    _, mon, day = label.split()
    return f"{year}-{MONTHS[mon]}-{int(day):02d}"


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    wb = openpyxl.load_workbook(sys.argv[1], data_only=True)

    rankings_by_date = defaultdict(list)
    for date, position, slug, name, players_ranked, pct, ranking_id in list(wb["rankings_long"].iter_rows(values_only=True))[1:]:
        rankings_by_date[date].append({"slug": slug, "rank": position, "fieldSize": players_ranked, "pct": pct})
    rankings = [{"date": party_date_to_iso(d), "players": sorted(v, key=lambda p: p["rank"])}
                for d, v in sorted(rankings_by_date.items(), key=lambda kv: party_date_to_iso(kv[0]))]

    record = defaultdict(lambda: {"w": 0, "l": 0})
    for game_id, date, slug, name, team, won in list(wb["game_players_long"].iter_rows(values_only=True))[1:]:
        record[slug]["w" if won else "l"] += 1
    record = {slug: {**wl, "gp": wl["w"] + wl["l"]} for slug, wl in record.items()}

    out = Path(__file__).parent / "poolean-external-data.js"
    out.write_text(
        "// Generated by build_poolean_data.py from the real Poolean site's own data export.\n"
        "// POOLEAN_RANKINGS: every party night's power-ranking result (all nights, not just ones with logged film).\n"
        "// POOLEAN_RECORD: each player's real overall win-loss across every game the site has recorded.\n"
        f"const POOLEAN_RANKINGS = {json.dumps(rankings, separators=(',', ':'))};\n"
        f"const POOLEAN_RECORD = {json.dumps(record, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"{len(rankings)} party nights, {len(record)} players with a real record -> {out}")


if __name__ == "__main__":
    main()
