"""Builds poolean-external-data.js from the real Poolean site's own data export (an .xlsx someone
downloads from the site's export feature). Things this app doesn't otherwise have:
  POOLEAN_RANKINGS      every party night's power-ranking result (rank/percentile per player), not
                         just the handful of nights that also have logged game film
  POOLEAN_RECORD         each player's real overall win-loss across every game the site has ever
                         recorded, not just the subset re-logged shot-by-shot in this app
  POOLEAN_TOGETHER       real pairwise win-loss as teammates, key "a|b" (slugs sorted)
  POOLEAN_AGAINST        real pairwise win-loss as opponents, key "a|b" (a's record facing b)
  POOLEAN_SEASON_CARDS   the site's own frozen end-of-season line per player (win%, power%, crowns,
                         best rank) -- the authoritative numbers, used instead of recomputing an
                         average by hand so this always matches the site exactly
Awards are NOT in this file on purpose -- the export's own README says per-voter ballots are
deleted when a party closes, and a season still being voted on has no results yet at all. Copy
AWARD_RESULTS's existing entries in app.js by hand from the site once a season's voting closes,
the same way it's always been done.
Usage: python build_poolean_data.py PATH_TO_EXPORT.xlsx
"""
import json
import sys
from collections import defaultdict
from itertools import combinations
from pathlib import Path

import openpyxl

MONTHS = {"Jan": "01", "Feb": "02", "Mar": "03", "Apr": "04", "May": "05", "Jun": "06",
          "Jul": "07", "Aug": "08", "Sep": "09", "Oct": "10", "Nov": "11", "Dec": "12"}


def party_date_to_iso(label, year=2026):
    # "Sun Jun 7" -> "2026-06-07". The export has no year (README: single season, no year in it).
    _, mon, day = label.split()
    return f"{year}-{MONTHS[mon]}-{int(day):02d}"


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    wb = openpyxl.load_workbook(sys.argv[1], data_only=True)

    rankings_by_date = defaultdict(list)
    for party_no, date, slug, name, rank, field_size, pct in list(wb["rankings_long"].iter_rows(values_only=True))[1:]:
        rankings_by_date[date].append({"slug": slug, "rank": rank, "fieldSize": field_size, "pct": pct})
    rankings = [{"date": party_date_to_iso(d), "players": sorted(v, key=lambda p: p["rank"])}
                for d, v in sorted(rankings_by_date.items(), key=lambda kv: party_date_to_iso(kv[0]))]

    record = defaultdict(lambda: {"w": 0, "l": 0})
    for game_no, date, slug, name, team, won in list(wb["game_players_long"].iter_rows(values_only=True))[1:]:
        record[slug]["w" if won else "l"] += 1
    record = {slug: {**wl, "gp": wl["w"] + wl["l"]} for slug, wl in record.items()}

    # Pairwise real history, straight off every game's own two rosters -- TOGETHER when a pair
    # shared a side (key is the pair sorted, since it's the same fact for both of them), AGAINST
    # per ordered pair (a's own record facing b, which is b's mirror image, not the same number).
    together = defaultdict(lambda: {"w": 0, "l": 0})
    against = defaultdict(lambda: {"w": 0, "l": 0})
    for game_no, gid, date, created, team_a, team_b, winner, a_size, b_size, live, events in list(wb["games"].iter_rows(values_only=True))[1:]:
        ta, tb = team_a.split("|"), team_b.split("|")
        a_won = winner == "A"
        for x, y in combinations(ta, 2):
            together["|".join(sorted((x, y)))]["w" if a_won else "l"] += 1
        for x, y in combinations(tb, 2):
            together["|".join(sorted((x, y)))]["w" if not a_won else "l"] += 1
        for x in ta:
            for y in tb:
                against[f"{x}|{y}"]["w" if a_won else "l"] += 1
                against[f"{y}|{x}"]["l" if a_won else "w"] += 1
    together = {k: {**v, "gp": v["w"] + v["l"]} for k, v in together.items()}
    against = {k: {**v, "gp": v["w"] + v["l"]} for k, v in against.items()}

    cards = {}
    if "season_cards" in wb.sheetnames:
        for slug, name, wins, losses, win_pct, power_pct, parties, crowns, best_rank in list(wb["season_cards"].iter_rows(values_only=True))[1:]:
            cards[slug] = {"w": wins, "l": losses, "winPct": win_pct, "powerPct": power_pct, "parties": parties, "crowns": crowns, "bestRank": best_rank}

    out = Path(__file__).parent / "poolean-external-data.js"
    out.write_text(
        "// Generated by build_poolean_data.py from the real Poolean site's own data export.\n"
        "// POOLEAN_RANKINGS: every party night's power-ranking result.\n"
        "// POOLEAN_RECORD: each player's real overall win-loss across every recorded game.\n"
        "// POOLEAN_TOGETHER / POOLEAN_AGAINST: real pairwise win-loss, as teammates / as opponents.\n"
        "// POOLEAN_SEASON_CARDS: the site's own frozen end-of-season line per player.\n"
        f"const POOLEAN_RANKINGS = {json.dumps(rankings, separators=(',', ':'))};\n"
        f"const POOLEAN_RECORD = {json.dumps(record, separators=(',', ':'))};\n"
        f"const POOLEAN_TOGETHER = {json.dumps(together, separators=(',', ':'))};\n"
        f"const POOLEAN_AGAINST = {json.dumps(against, separators=(',', ':'))};\n"
        f"const POOLEAN_SEASON_CARDS = {json.dumps(cards, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"{len(rankings)} party nights, {len(record)} players, {len(together)} pairs together, "
          f"{len(against)} pairs against, {len(cards)} season cards -> {out}")


if __name__ == "__main__":
    main()
