"""Writes ../shot-arcs-data.js, the small table the player page uses for its "Shot Arc" panel.
One row per traced shot that can be tied to a single logged shot: [gameId, videoTime, secondsInAir,
peakTiming, archRelative]. No names in it: the app matches rows to logged shots by game and video time.
  secondsInAir  real seconds from release to the hoop (does not depend on the camera)
  peakTiming    how far through the flight the ball reaches its highest point (0 to 1)
  archRelative  arc height for its length, divided by the average for the same recording, so 1.0 is a
                typical arc on that camera (pixel shapes differ from one recording to the next)
Rows whose attribution is ambiguous (another logged shot lands within a second of the flight) are left out.
Run analyze_arcs.py first (it writes shot_arcs_features.csv). Usage: python build_arc_profile_data.py"""
import csv
import json
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).parent
rows = [r for r in csv.DictReader(open(HERE / "shot_arcs_features.csv", encoding="utf-8")) if r["attribution"] == "clear"]
by_rec = defaultdict(list)
for r in rows:
    by_rec[r["recording"]].append(float(r["arch_ratio"]))
mean_ratio = {k: sum(v) / len(v) for k, v in by_rec.items()}

out = []
for r in sorted(rows, key=lambda r: r["key"]):
    game, whole, frac = r["key"].rsplit("_", 2)
    out.append([game, float(f"{whole}.{frac}"), round(float(r["flight_s"]), 3), round(float(r["apex_frac"]), 3),
                round(float(r["arch_ratio"]) / mean_ratio[r["recording"]], 3)])
text = ("// Generated by shot-arc/build_arc_profile_data.py from the traced shots. Do not edit by hand.\n"
        "// Rows: [gameId, videoTime, secondsInAir, peakTiming, archRelative]\n"
        f"const SHOT_ARC_DATA = {json.dumps(out, separators=(',', ':'))};\n")
(HERE.parent / "shot-arcs-data.js").write_text(text, encoding="utf-8")
print(f"{len(out)} rows written ({len(rows)} clear of {sum(1 for _ in csv.DictReader(open(HERE / 'shot_arcs_features.csv', encoding='utf-8')))} traced)")
