"""
Step 1 of the per-shot pipeline (see standalone-shot-arc-plan.md): pull frames from roughly
1.5-2s before a shot's videoTime through 0.5s after (release through landing), using ffmpeg
seeking the same way the existing dashboard already does for clip review.
"""
import subprocess
import shutil
from pathlib import Path

PRE_ROLL = 3.0  # widened from 1.8s after real hand-labeling on 02_Evan_make: the ball wasn't
                 # visible at all for the first ~0.57s of a 1.8s pre-roll, and was already near
                 # its peak height and roughly level (barely changing) once it appeared -- signs
                 # the true release happened before the window even started, so the label data
                 # was catching the back half of the arc (peak, descent, net-settle) and missing
                 # release/rise entirely. See FINDINGS.md.
POST_ROLL = 0.4  # shrunk slightly to compensate -- by the old window's own last ~0.3s the ball
                  # had already settled into the net with no new flight information, based on the
                  # same real label (y_from_bottom oscillating in a narrow band, not still falling)
FPS = 30  # matches typical source footage; frame-detection step doesn't need more than this

FRAMES_ROOT = Path(__file__).parent / "frames"


def extract_shot_frames(video_file: str, local_time: float, shot_key: str) -> Path:
    start = max(0.0, local_time - PRE_ROLL)
    duration = PRE_ROLL + POST_ROLL
    out_dir = FRAMES_ROOT / shot_key
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    # -ss before -i: fast seek to the nearest keyframe, then a short accurate decode from there.
    # A real pool video's keyframe interval can put "before -i" seeking off by a second or more,
    # which is why -ss appears a second time (after -i) too: the first does the coarse/fast jump,
    # the second trims the decoded output back to the exact intended start.
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-ss", str(max(0.0, start - 2.0)), "-i", video_file,
        "-ss", "2.0", "-t", str(duration),
        "-vf", f"fps={FPS}",
        str(out_dir / "frame_%04d.png"),
    ]
    subprocess.run(cmd, check=True)
    frames = sorted(out_dir.glob("frame_*.png"))
    return out_dir, start, frames


def write_labeling_manifest():
    """Scans frames/ directly (not sample_shots.json) so it stays in sync with whatever's
    actually on disk, including frames added by hand later. Written as a plain <script>-loadable
    .js file (not JSON) so the labeling tool in the main dashboard can pick it up with a normal
    <script src> tag -- fetch()'ing a local file hits file:// CORS restrictions in Chrome, a
    script tag doesn't, same reason viewer-seed-data.js is a .js file instead of a .json one.
    """
    import json
    shots = []
    for shot_dir in sorted(FRAMES_ROOT.iterdir()) if FRAMES_ROOT.exists() else []:
        if not shot_dir.is_dir():
            continue
        frames = sorted(shot_dir.glob("frame_*.png"))
        if frames:
            shots.append({"key": shot_dir.name, "frameCount": len(frames), "fps": FPS})
    manifest_path = Path(__file__).parent / "labeling-manifest.js"
    manifest_path.write_text(
        "// Auto-generated by extract_frames.py -- lists whatever's currently in shot-arc/frames/\n"
        "// so the Shot Arc Hand-Labeling tool (dashboard Export tab) can load frames directly by\n"
        "// path instead of requiring a manual folder upload. Regenerate by re-running\n"
        "// extract_frames.py, or standalone via write_labeling_manifest().\n"
        f"const SHOT_ARC_LABEL_MANIFEST = {json.dumps(shots, indent=2)};\n"
    )
    return manifest_path, shots


if __name__ == "__main__":
    import json
    shots = json.loads((Path(__file__).parent / "sample_shots.json").read_text())
    for i, s in enumerate(shots):
        key = f"{i:02d}_{s['shooter']}_{'make' if s['made'] else 'miss'}"
        out_dir, start, frames = extract_shot_frames(s["video_file"], s["video_time_local"], key)
        print(f"{key}: {len(frames)} frames -> {out_dir} (clip starts at local t={start:.2f}s)")

    manifest_path, manifest_shots = write_labeling_manifest()
    print(f"\nWrote {manifest_path} ({len(manifest_shots)} shots available to label)")
